name: Deploy

on:
  push:
    branches:
    - versions/*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/checkout@v2
        id: checkout-repo
        name: Checkout Repository

      - uses: actions/setup-node@v2
        name: Setup node
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
        name: Install dependencies

      - run: npm run build:lib
        name: Build library

      - run: npm publish --access public --verbose
        working-directory: ./dist/@mdcc/form-facade
        name: Deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
